# ===========================================================
#  MyTicket — Offline Mode Overrides
# ===========================================================

app.mode=offline
app.hcaptcha.enabled=false
